export interface Country {
  code: string;
  name: string;
  currency: string;
  regions: string[];
}

export const countries: Country[] = [
  { code: "AF", name: "Afghanistan", currency: "AFN", regions: ["Kabul", "Kandahar", "Herat", "Mazar-i-Sharif", "Jalalabad"] },
  { code: "AL", name: "Albania", currency: "ALL", regions: ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër"] },
  { code: "DZ", name: "Algeria", currency: "DZD", regions: ["Algiers", "Oran", "Constantine", "Annaba", "Blida"] },
  { code: "AD", name: "Andorra", currency: "EUR", regions: ["Andorra la Vella", "Escaldes-Engordany", "Encamp", "La Massana"] },
  { code: "AO", name: "Angola", currency: "AOA", regions: ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango"] },
  { code: "AG", name: "Antigua and Barbuda", currency: "XCD", regions: ["Saint John's", "All Saints", "Liberta"] },
  { code: "AR", name: "Argentina", currency: "ARS", regions: ["Buenos Aires", "Córdoba", "Santa Fe", "Mendoza", "Tucumán", "Entre Ríos", "Salta", "Chaco", "Corrientes", "Misiones"] },
  { code: "AM", name: "Armenia", currency: "AMD", regions: ["Yerevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan"] },
  { code: "AU", name: "Australia", currency: "AUD", regions: ["New South Wales", "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia", "Australian Capital Territory", "Northern Territory"] },
  { code: "AT", name: "Austria", currency: "EUR", regions: ["Vienna", "Lower Austria", "Upper Austria", "Styria", "Tyrol", "Carinthia", "Salzburg", "Vorarlberg", "Burgenland"] },
  { code: "AZ", name: "Azerbaijan", currency: "AZN", regions: ["Baku", "Ganja", "Sumqayit", "Mingachevir", "Lankaran"] },
  { code: "BS", name: "Bahamas", currency: "BSD", regions: ["Nassau", "Freeport", "West Grand Bahama", "Cooper's Town"] },
  { code: "BH", name: "Bahrain", currency: "BHD", regions: ["Manama", "Riffa", "Muharraq", "Hamad Town"] },
  { code: "BD", name: "Bangladesh", currency: "BDT", regions: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet", "Barisal", "Rangpur", "Mymensingh"] },
  { code: "BB", name: "Barbados", currency: "BBD", regions: ["Bridgetown", "Speightstown", "Oistins", "Holetown"] },
  { code: "BY", name: "Belarus", currency: "BYN", regions: ["Minsk", "Gomel", "Mogilev", "Vitebsk", "Grodno", "Brest"] },
  { code: "BE", name: "Belgium", currency: "EUR", regions: ["Flanders", "Wallonia", "Brussels"] },
  { code: "BZ", name: "Belize", currency: "BZD", regions: ["Belize City", "San Ignacio", "Orange Walk", "Belmopan"] },
  { code: "BJ", name: "Benin", currency: "XOF", regions: ["Cotonou", "Porto-Novo", "Parakou", "Djougou"] },
  { code: "BT", name: "Bhutan", currency: "BTN", regions: ["Thimphu", "Phuntsholing", "Paro", "Punakha"] },
  { code: "BO", name: "Bolivia", currency: "BOB", regions: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro"] },
  { code: "BA", name: "Bosnia and Herzegovina", currency: "BAM", regions: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"] },
  { code: "BW", name: "Botswana", currency: "BWP", regions: ["Gaborone", "Francistown", "Maun", "Serowe"] },
  { code: "BR", name: "Brazil", currency: "BRL", regions: ["São Paulo", "Rio de Janeiro", "Minas Gerais", "Bahia", "Paraná", "Rio Grande do Sul", "Pernambuco", "Ceará", "Pará", "Santa Catarina"] },
  { code: "BN", name: "Brunei", currency: "BND", regions: ["Bandar Seri Begawan", "Kuala Belait", "Seria", "Tutong"] },
  { code: "BG", name: "Bulgaria", currency: "BGN", regions: ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"] },
  { code: "BF", name: "Burkina Faso", currency: "XOF", regions: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya"] },
  { code: "BI", name: "Burundi", currency: "BIF", regions: ["Bujumbura", "Gitega", "Muyinga", "Ruyigi"] },
  { code: "KH", name: "Cambodia", currency: "KHR", regions: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville"] },
  { code: "CM", name: "Cameroon", currency: "XAF", regions: ["Douala", "Yaoundé", "Garoua", "Bamenda"] },
  { code: "CA", name: "Canada", currency: "CAD", regions: ["Alberta", "British Columbia", "Manitoba", "New Brunswick", "Newfoundland and Labrador", "Nova Scotia", "Ontario", "Prince Edward Island", "Quebec", "Saskatchewan", "Northwest Territories", "Nunavut", "Yukon"] },
  { code: "CV", name: "Cape Verde", currency: "CVE", regions: ["Praia", "Mindelo", "Santa Maria", "Assomada"] },
  { code: "CF", name: "Central African Republic", currency: "XAF", regions: ["Bangui", "Bimbo", "Berbérati", "Carnot"] },
  { code: "TD", name: "Chad", currency: "XAF", regions: ["N'Djamena", "Moundou", "Sarh", "Abéché"] },
  { code: "CL", name: "Chile", currency: "CLP", regions: ["Santiago", "Valparaíso", "Concepción", "La Serena", "Antofagasta"] },
  { code: "CN", name: "China", currency: "CNY", regions: ["Beijing", "Shanghai", "Guangdong", "Jiangsu", "Zhejiang", "Shandong", "Henan", "Sichuan", "Hubei", "Hunan", "Anhui", "Hebei", "Shaanxi", "Jiangxi", "Liaoning", "Fujian", "Heilongjiang", "Shanxi", "Guizhou", "Chongqing", "Jilin", "Gansu", "Inner Mongolia", "Yunnan", "Guangxi", "Xinjiang", "Hainan", "Ningxia", "Qinghai", "Tibet"] },
  { code: "CO", name: "Colombia", currency: "COP", regions: ["Bogotá", "Antioquia", "Valle del Cauca", "Atlántico", "Santander"] },
  { code: "KM", name: "Comoros", currency: "KMF", regions: ["Moroni", "Mutsamudu", "Fomboni", "Domoni"] },
  { code: "CG", name: "Congo", currency: "XAF", regions: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi"] },
  { code: "CD", name: "Congo (DRC)", currency: "CDF", regions: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kananga", "Kisangani"] },
  { code: "CR", name: "Costa Rica", currency: "CRC", regions: ["San José", "Alajuela", "Cartago", "Heredia", "Limón"] },
  { code: "HR", name: "Croatia", currency: "EUR", regions: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"] },
  { code: "CU", name: "Cuba", currency: "CUP", regions: ["Havana", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"] },
  { code: "CY", name: "Cyprus", currency: "EUR", regions: ["Nicosia", "Limassol", "Larnaca", "Paphos", "Famagusta"] },
  { code: "CZ", name: "Czech Republic", currency: "CZK", regions: ["Prague", "Central Bohemian", "South Moravian", "Moravian-Silesian", "Olomouc", "Zlín", "Plzeň", "South Bohemian", "Hradec Králové", "Pardubice"] },
  { code: "DK", name: "Denmark", currency: "DKK", regions: ["Capital Region", "Central Denmark", "North Denmark", "Zealand", "South Denmark"] },
  { code: "DJ", name: "Djibouti", currency: "DJF", regions: ["Djibouti City", "Ali Sabieh", "Dikhil", "Tadjourah"] },
  { code: "DM", name: "Dominica", currency: "XCD", regions: ["Roseau", "Portsmouth", "Marigot", "Berekua"] },
  { code: "DO", name: "Dominican Republic", currency: "DOP", regions: ["Santo Domingo", "Santiago", "La Vega", "San Cristóbal"] },
  { code: "EC", name: "Ecuador", currency: "USD", regions: ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Machala"] },
  { code: "EG", name: "Egypt", currency: "EGP", regions: ["Cairo", "Giza", "Alexandria", "Qalyubia", "Sharqia", "Dakahlia", "Beheira", "Minya", "Asyut", "Sohag"] },
  { code: "SV", name: "El Salvador", currency: "USD", regions: ["San Salvador", "Santa Ana", "San Miguel", "Soyapango"] },
  { code: "GQ", name: "Equatorial Guinea", currency: "XAF", regions: ["Malabo", "Bata", "Ebebiyin", "Aconibe"] },
  { code: "ER", name: "Eritrea", currency: "ERN", regions: ["Asmara", "Keren", "Massawa", "Assab"] },
  { code: "EE", name: "Estonia", currency: "EUR", regions: ["Tallinn", "Tartu", "Narva", "Pärnu"] },
  { code: "SZ", name: "Eswatini", currency: "SZL", regions: ["Mbabane", "Manzini", "Lobamba", "Siteki"] },
  { code: "ET", name: "Ethiopia", currency: "ETB", regions: ["Addis Ababa", "Dire Dawa", "Mek'ele", "Gondar", "Bahir Dar"] },
  { code: "FJ", name: "Fiji", currency: "FJD", regions: ["Suva", "Lautoka", "Nadi", "Labasa"] },
  { code: "FI", name: "Finland", currency: "EUR", regions: ["Uusimaa", "Pirkanmaa", "Southwest Finland", "North Ostrobothnia", "Central Finland", "Kanta-Häme", "Satakunta", "Päijät-Häme", "Kymenlaakso", "South Karelia"] },
  { code: "FR", name: "France", currency: "EUR", regions: ["Île-de-France", "Provence-Alpes-Côte d'Azur", "Auvergne-Rhône-Alpes", "Nouvelle-Aquitaine", "Occitanie", "Hauts-de-France", "Brittany", "Normandy", "Grand Est", "Centre-Val de Loire", "Bourgogne-Franche-Comté", "Pays de la Loire"] },
  { code: "GA", name: "Gabon", currency: "XAF", regions: ["Libreville", "Port-Gentil", "Franceville", "Oyem"] },
  { code: "GM", name: "Gambia", currency: "GMD", regions: ["Banjul", "Serekunda", "Brikama", "Bakau"] },
  { code: "GE", name: "Georgia", currency: "GEL", regions: ["Tbilisi", "Kutaisi", "Batumi", "Rustavi", "Zugdidi"] },
  { code: "DE", name: "Germany", currency: "EUR", regions: ["Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen", "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern", "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland", "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia"] },
  { code: "GH", name: "Ghana", currency: "GHS", regions: ["Greater Accra", "Ashanti", "Western", "Eastern", "Central"] },
  { code: "GR", name: "Greece", currency: "EUR", regions: ["Attica", "Central Macedonia", "Thessaly", "Crete", "Western Greece", "Peloponnese", "Eastern Macedonia and Thrace", "Epirus", "Ionian Islands", "South Aegean"] },
  { code: "GD", name: "Grenada", currency: "XCD", regions: ["Saint George's", "Gouyave", "Grenville", "Victoria"] },
  { code: "GT", name: "Guatemala", currency: "GTQ", regions: ["Guatemala City", "Quetzaltenango", "Escuintla", "Mixco"] },
  { code: "GN", name: "Guinea", currency: "GNF", regions: ["Conakry", "Nzérékoré", "Kankan", "Kindia"] },
  { code: "GW", name: "Guinea-Bissau", currency: "XOF", regions: ["Bissau", "Bafatá", "Gabú", "Bissorã"] },
  { code: "GY", name: "Guyana", currency: "GYD", regions: ["Georgetown", "Linden", "New Amsterdam", "Anna Regina"] },
  { code: "HT", name: "Haiti", currency: "HTG", regions: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Les Cayes"] },
  { code: "HN", name: "Honduras", currency: "HNL", regions: ["Tegucigalpa", "San Pedro Sula", "Choloma", "La Ceiba"] },
  { code: "HU", name: "Hungary", currency: "HUF", regions: ["Budapest", "Pest", "Borsod-Abaúj-Zemplén", "Győr-Moson-Sopron", "Hajdú-Bihar"] },
  { code: "IS", name: "Iceland", currency: "ISK", regions: ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri"] },
  { code: "IN", name: "India", currency: "INR", regions: ["Maharashtra", "Uttar Pradesh", "Bihar", "West Bengal", "Madhya Pradesh", "Tamil Nadu", "Rajasthan", "Karnataka", "Gujarat", "Andhra Pradesh", "Odisha", "Telangana", "Kerala", "Jharkhand", "Assam", "Punjab", "Chhattisgarh", "Haryana", "Delhi", "Jammu and Kashmir", "Uttarakhand", "Himachal Pradesh", "Tripura", "Meghalaya", "Manipur", "Nagaland", "Goa", "Arunachal Pradesh", "Mizoram", "Sikkim"] },
  { code: "ID", name: "Indonesia", currency: "IDR", regions: ["Jakarta", "West Java", "East Java", "Central Java", "Banten", "North Sumatra", "South Sulawesi", "Riau", "Lampung", "West Sumatra"] },
  { code: "IR", name: "Iran", currency: "IRR", regions: ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz", "Tabriz"] },
  { code: "IQ", name: "Iraq", currency: "IQD", regions: ["Baghdad", "Basra", "Mosul", "Erbil", "Sulaymaniyah"] },
  { code: "IE", name: "Ireland", currency: "EUR", regions: ["Leinster", "Munster", "Connacht", "Ulster"] },
  { code: "IL", name: "Israel", currency: "ILS", regions: ["Jerusalem", "Tel Aviv", "Haifa", "Central", "Southern", "Northern"] },
  { code: "IT", name: "Italy", currency: "EUR", regions: ["Lazio", "Lombardy", "Campania", "Sicily", "Veneto", "Emilia-Romagna", "Piedmont", "Apulia", "Tuscany", "Calabria", "Sardinia", "Liguria", "Marche", "Abruzzo", "Friuli-Venezia Giulia", "Trentino-Alto Adige", "Umbria", "Basilicata", "Molise", "Aosta Valley"] },
  { code: "JM", name: "Jamaica", currency: "JMD", regions: ["Kingston", "Montego Bay", "Spanish Town", "Portmore"] },
  { code: "JP", name: "Japan", currency: "JPY", regions: ["Tokyo", "Osaka", "Kanagawa", "Aichi", "Saitama", "Chiba", "Hyogo", "Hokkaido", "Fukuoka", "Shizuoka"] },
  { code: "JO", name: "Jordan", currency: "JOD", regions: ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba"] },
  { code: "KZ", name: "Kazakhstan", currency: "KZT", regions: ["Almaty", "Nur-Sultan", "Shymkent", "Karaganda", "Aktobe"] },
  { code: "KE", name: "Kenya", currency: "KES", regions: ["Nairobi", "Mombasa", "Nakuru", "Kisumu", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Kakamega"] },
  { code: "KI", name: "Kiribati", currency: "AUD", regions: ["South Tarawa", "Betio", "Bikenibeu"] },
  { code: "KW", name: "Kuwait", currency: "KWD", regions: ["Kuwait City", "Hawalli", "Farwaniya", "Jahra"] },
  { code: "KG", name: "Kyrgyzstan", currency: "KGS", regions: ["Bishkek", "Osh", "Jalal-Abad", "Karakol"] },
  { code: "LA", name: "Laos", currency: "LAK", regions: ["Vientiane", "Pakse", "Savannakhet", "Luang Prabang"] },
  { code: "LV", name: "Latvia", currency: "EUR", regions: ["Riga", "Daugavpils", "Liepāja", "Jelgava"] },
  { code: "LB", name: "Lebanon", currency: "LBP", regions: ["Beirut", "Tripoli", "Sidon", "Tyre", "Nabatieh"] },
  { code: "LS", name: "Lesotho", currency: "LSL", regions: ["Maseru", "Teyateyaneng", "Mafeteng", "Hlotse"] },
  { code: "LR", name: "Liberia", currency: "LRD", regions: ["Monrovia", "Gbarnga", "Buchanan", "Kakata"] },
  { code: "LY", name: "Libya", currency: "LYD", regions: ["Tripoli", "Benghazi", "Misrata", "Bayda"] },
  { code: "LI", name: "Liechtenstein", currency: "CHF", regions: ["Vaduz", "Schaan", "Balzers", "Triesen"] },
  { code: "LT", name: "Lithuania", currency: "EUR", regions: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai"] },
  { code: "LU", name: "Luxembourg", currency: "EUR", regions: ["Luxembourg City", "Esch-sur-Alzette", "Differdange", "Dudelange"] },
  { code: "MG", name: "Madagascar", currency: "MGA", regions: ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga"] },
  { code: "MW", name: "Malawi", currency: "MWK", regions: ["Lilongwe", "Blantyre", "Mzuzu", "Zomba"] },
  { code: "MY", name: "Malaysia", currency: "MYR", regions: ["Selangor", "Johor", "Sabah", "Sarawak", "Perak", "Penang", "Kedah", "Kelantan", "Pahang", "Terengganu"] },
  { code: "MV", name: "Maldives", currency: "MVR", regions: ["Malé", "Addu City", "Fuvahmulah", "Kulhudhuffushi"] },
  { code: "ML", name: "Mali", currency: "XOF", regions: ["Bamako", "Sikasso", "Mopti", "Koutiala"] },
  { code: "MT", name: "Malta", currency: "EUR", regions: ["Valletta", "Birkirkara", "Mosta", "Qormi"] },
  { code: "MH", name: "Marshall Islands", currency: "USD", regions: ["Majuro", "Ebeye", "Arno", "Jaluit"] },
  { code: "MR", name: "Mauritania", currency: "MRU", regions: ["Nouakchott", "Nouadhibou", "Kaédi", "Rosso"] },
  { code: "MU", name: "Mauritius", currency: "MUR", regions: ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe"] },
  { code: "MX", name: "Mexico", currency: "MXN", regions: ["Mexico City", "State of Mexico", "Jalisco", "Veracruz", "Puebla", "Guanajuato", "Chiapas", "Nuevo León", "Michoacán", "Oaxaca"] },
  { code: "FM", name: "Micronesia", currency: "USD", regions: ["Palikir", "Weno", "Kolonia", "Tofol"] },
  { code: "MD", name: "Moldova", currency: "MDL", regions: ["Chișinău", "Tiraspol", "Bălți", "Bender"] },
  { code: "MC", name: "Monaco", currency: "EUR", regions: ["Monaco-Ville", "Monte Carlo", "La Condamine", "Fontvieille"] },
  { code: "MN", name: "Mongolia", currency: "MNT", regions: ["Ulaanbaatar", "Erdenet", "Darkhan", "Choibalsan"] },
  { code: "ME", name: "Montenegro", currency: "EUR", regions: ["Podgorica", "Nikšić", "Pljevlja", "Bijelo Polje"] },
  { code: "MA", name: "Morocco", currency: "MAD", regions: ["Casablanca", "Rabat", "Fès", "Marrakesh", "Tangier"] },
  { code: "MZ", name: "Mozambique", currency: "MZN", regions: ["Maputo", "Matola", "Nampula", "Beira"] },
  { code: "MM", name: "Myanmar", currency: "MMK", regions: ["Yangon", "Mandalay", "Naypyidaw", "Mawlamyine"] },
  { code: "NA", name: "Namibia", currency: "NAD", regions: ["Windhoek", "Rundu", "Walvis Bay", "Oshakati"] },
  { code: "NR", name: "Nauru", currency: "AUD", regions: ["Yaren", "Denigomodu", "Aiwo", "Anabar"] },
  { code: "NP", name: "Nepal", currency: "NPR", regions: ["Kathmandu", "Pokhara", "Lalitpur", "Bharatpur", "Biratnagar"] },
  { code: "NL", name: "Netherlands", currency: "EUR", regions: ["North Holland", "South Holland", "North Brabant", "Gelderland", "Utrecht", "Limburg", "Overijssel", "Friesland", "Groningen", "Zeeland", "Drenthe", "Flevoland"] },
  { code: "NZ", name: "New Zealand", currency: "NZD", regions: ["Auckland", "Wellington", "Canterbury", "Waikato", "Bay of Plenty", "Otago", "Manawatu-Wanganui", "Northland", "Hawke's Bay", "Taranaki"] },
  { code: "NI", name: "Nicaragua", currency: "NIO", regions: ["Managua", "León", "Masaya", "Matagalpa"] },
  { code: "NE", name: "Niger", currency: "XOF", regions: ["Niamey", "Zinder", "Maradi", "Agadez"] },
  { code: "NG", name: "Nigeria", currency: "NGN", regions: ["Lagos", "Kano", "Kaduna", "Rivers", "Oyo", "Ogun", "Imo", "Delta", "Edo", "Anambra"] },
  { code: "KP", name: "North Korea", currency: "KPW", regions: ["Pyongyang", "Hamhung", "Chongjin", "Nampo"] },
  { code: "MK", name: "North Macedonia", currency: "MKD", regions: ["Skopje", "Bitola", "Kumanovo", "Prilep"] },
  { code: "NO", name: "Norway", currency: "NOK", regions: ["Oslo", "Viken", "Vestland", "Trøndelag", "Rogaland", "Innlandet", "Vestfold og Telemark", "Agder", "Møre og Romsdal", "Nordland", "Troms og Finnmark"] },
  { code: "OM", name: "Oman", currency: "OMR", regions: ["Muscat", "Salalah", "Sohar", "Nizwa"] },
  { code: "PK", name: "Pakistan", currency: "PKR", regions: ["Punjab", "Sindh", "Khyber Pakhtunkhwa", "Balochistan", "Islamabad"] },
  { code: "PW", name: "Palau", currency: "USD", regions: ["Koror", "Airai", "Melekeok", "Peleliu"] },
  { code: "PA", name: "Panama", currency: "PAB", regions: ["Panama City", "San Miguelito", "Tocumen", "David"] },
  { code: "PG", name: "Papua New Guinea", currency: "PGK", regions: ["Port Moresby", "Lae", "Mount Hagen", "Madang"] },
  { code: "PY", name: "Paraguay", currency: "PYG", regions: ["Asunción", "Ciudad del Este", "San Lorenzo", "Luque"] },
  { code: "PE", name: "Peru", currency: "PEN", regions: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Piura"] },
  { code: "PH", name: "Philippines", currency: "PHP", regions: ["Metro Manila", "Calabarzon", "Central Luzon", "Central Visayas", "Western Visayas", "Davao Region", "Northern Mindanao", "Ilocos Region", "SOCCSKSARGEN", "Zamboanga Peninsula"] },
  { code: "PL", name: "Poland", currency: "PLN", regions: ["Masovian", "Silesian", "Greater Poland", "Lesser Poland", "Lower Silesian", "Pomeranian", "Łódź", "West Pomeranian", "Kuyavian-Pomeranian", "Lublin"] },
  { code: "PT", name: "Portugal", currency: "EUR", regions: ["Lisbon", "Porto", "Faro", "Setúbal", "Braga", "Coimbra", "Aveiro", "Leiria", "Santarém", "Viseu"] },
  { code: "QA", name: "Qatar", currency: "QAR", regions: ["Doha", "Al Rayyan", "Umm Salal", "Al Wakrah"] },
  { code: "RO", name: "Romania", currency: "RON", regions: ["Bucharest", "Cluj", "Timișoara", "Iași", "Constanța"] },
  { code: "RU", name: "Russia", currency: "RUB", regions: ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan", "Nizhny Novgorod", "Chelyabinsk", "Samara", "Omsk", "Rostov-on-Don"] },
  { code: "RW", name: "Rwanda", currency: "RWF", regions: ["Kigali", "Butare", "Gitarama", "Ruhengeri"] },
  { code: "KN", name: "Saint Kitts and Nevis", currency: "XCD", regions: ["Basseterre", "Charlestown", "Sandy Point", "Cayon"] },
  { code: "LC", name: "Saint Lucia", currency: "XCD", regions: ["Castries", "Vieux Fort", "Micoud", "Soufrière"] },
  { code: "VC", name: "Saint Vincent and the Grenadines", currency: "XCD", regions: ["Kingstown", "Georgetown", "Barrouallie", "Port Elizabeth"] },
  { code: "WS", name: "Samoa", currency: "WST", regions: ["Apia", "Vaitele", "Faleula", "Siusega"] },
  { code: "SM", name: "San Marino", currency: "EUR", regions: ["San Marino", "Serravalle", "Borgo Maggiore", "Domagnano"] },
  { code: "ST", name: "São Tomé and Príncipe", currency: "STN", regions: ["São Tomé", "Santo António", "Trindade", "Santana"] },
  { code: "SA", name: "Saudi Arabia", currency: "SAR", regions: ["Riyadh", "Makkah", "Eastern Province", "Asir", "Madinah", "Qasim", "Tabuk", "Hail", "Northern Borders", "Jizan"] },
  { code: "SN", name: "Senegal", currency: "XOF", regions: ["Dakar", "Thiès", "Kaolack", "Ziguinchor", "Saint-Louis"] },
  { code: "RS", name: "Serbia", currency: "RSD", regions: ["Belgrade", "Novi Sad", "Niš", "Kragujevac"] },
  { code: "SC", name: "Seychelles", currency: "SCR", regions: ["Victoria", "Anse Boileau", "Beau Vallon", "Cascade"] },
  { code: "SL", name: "Sierra Leone", currency: "SLL", regions: ["Freetown", "Bo", "Kenema", "Makeni"] },
  { code: "SG", name: "Singapore", currency: "SGD", regions: ["Central Region", "East Region", "North Region", "North-East Region", "West Region"] },
  { code: "SK", name: "Slovakia", currency: "EUR", regions: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra"] },
  { code: "SI", name: "Slovenia", currency: "EUR", regions: ["Ljubljana", "Maribor", "Celje", "Kranj"] },
  { code: "SB", name: "Solomon Islands", currency: "SBD", regions: ["Honiara", "Gizo", "Auki", "Kirakira"] },
  { code: "SO", name: "Somalia", currency: "SOS", regions: ["Mogadishu", "Hargeisa", "Berbera", "Kismayo"] },
  { code: "ZA", name: "South Africa", currency: "ZAR", regions: ["Gauteng", "KwaZulu-Natal", "Western Cape", "Eastern Cape", "Limpopo", "Mpumalanga", "North West", "Free State", "Northern Cape"] },
  { code: "KR", name: "South Korea", currency: "KRW", regions: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju", "Ulsan", "Gyeonggi", "Gangwon", "North Chungcheong"] },
  { code: "SS", name: "South Sudan", currency: "SSP", regions: ["Juba", "Wau", "Malakal", "Yei"] },
  { code: "ES", name: "Spain", currency: "EUR", regions: ["Andalusia", "Catalonia", "Madrid", "Valencia", "Galicia", "Castile and León", "Basque Country", "Canary Islands", "Castilla-La Mancha", "Murcia", "Aragon", "Balearic Islands", "Extremadura", "Asturias", "Navarre", "Cantabria", "La Rioja"] },
  { code: "LK", name: "Sri Lanka", currency: "LKR", regions: ["Western", "Central", "Southern", "Northern", "Eastern"] },
  { code: "SD", name: "Sudan", currency: "SDG", regions: ["Khartoum", "Omdurman", "Port Sudan", "Kassala"] },
  { code: "SR", name: "Suriname", currency: "SRD", regions: ["Paramaribo", "Lelydorp", "Nieuw Nickerie", "Moengo"] },
  { code: "SE", name: "Sweden", currency: "SEK", regions: ["Stockholm", "Västra Götaland", "Skåne", "Östergötland", "Uppsala", "Jönköping", "Halland", "Örebro", "Västmanland", "Södermanland"] },
  { code: "CH", name: "Switzerland", currency: "CHF", regions: ["Zurich", "Bern", "Vaud", "Aargau", "Geneva", "Lucerne", "Ticino", "St. Gallen", "Valais", "Thurgau"] },
  { code: "SY", name: "Syria", currency: "SYP", regions: ["Damascus", "Aleppo", "Homs", "Latakia", "Hama"] },
  { code: "TW", name: "Taiwan", currency: "TWD", regions: ["Taipei", "New Taipei", "Kaohsiung", "Taichung", "Tainan"] },
  { code: "TJ", name: "Tajikistan", currency: "TJS", regions: ["Dushanbe", "Khujand", "Kulob", "Qurghonteppa"] },
  { code: "TZ", name: "Tanzania", currency: "TZS", regions: ["Dar es Salaam", "Mwanza", "Arusha", "Dodoma", "Mbeya"] },
  { code: "TH", name: "Thailand", currency: "THB", regions: ["Bangkok", "Chiang Mai", "Nakhon Ratchasima", "Khon Kaen", "Chonburi", "Songkhla", "Nakhon Si Thammarat", "Udon Thani", "Surat Thani", "Chiang Rai"] },
  { code: "TL", name: "Timor-Leste", currency: "USD", regions: ["Dili", "Baucau", "Maliana", "Suai"] },
  { code: "TG", name: "Togo", currency: "XOF", regions: ["Lomé", "Sokodé", "Kara", "Atakpamé"] },
  { code: "TO", name: "Tonga", currency: "TOP", regions: ["Nuku'alofa", "Neiafu", "Haveluloto", "Vaini"] },
  { code: "TT", name: "Trinidad and Tobago", currency: "TTD", regions: ["Port of Spain", "San Fernando", "Chaguanas", "Arima"] },
  { code: "TN", name: "Tunisia", currency: "TND", regions: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"] },
  { code: "TR", name: "Turkey", currency: "TRY", regions: ["Istanbul", "Ankara", "Izmir", "Bursa", "Adana", "Gaziantep", "Konya", "Antalya", "Kayseri", "Mersin"] },
  { code: "TM", name: "Turkmenistan", currency: "TMT", regions: ["Ashgabat", "Türkmenabat", "Daşoguz", "Mary"] },
  { code: "TV", name: "Tuvalu", currency: "AUD", regions: ["Funafuti", "Vaiaku", "Alapi", "Asau"] },
  { code: "UG", name: "Uganda", currency: "UGX", regions: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja"] },
  { code: "UA", name: "Ukraine", currency: "UAH", regions: ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Donetsk", "Lviv"] },
  { code: "AE", name: "United Arab Emirates", currency: "AED", regions: ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Ras Al Khaimah", "Fujairah", "Umm Al Quwain"] },
  { code: "GB", name: "United Kingdom", currency: "GBP", regions: ["England", "Scotland", "Wales", "Northern Ireland"] },
  { code: "US", name: "United States", currency: "USD", regions: ["Alabama", "Alaska", "Arizona", "Arkansas", "California", "Colorado", "Connecticut", "Delaware", "Florida", "Georgia", "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa", "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland", "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri", "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey", "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio", "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina", "South Dakota", "Tennessee", "Texas", "Utah", "Vermont", "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming", "District of Columbia", "Puerto Rico", "Guam", "U.S. Virgin Islands"] },
  { code: "UY", name: "Uruguay", currency: "UYU", regions: ["Montevideo", "Salto", "Paysandú", "Las Piedras", "Rivera"] },
  { code: "UZ", name: "Uzbekistan", currency: "UZS", regions: ["Tashkent", "Samarkand", "Namangan", "Andijan", "Bukhara"] },
  { code: "VU", name: "Vanuatu", currency: "VUV", regions: ["Port Vila", "Luganville", "Norsup", "Isangel"] },
  { code: "VA", name: "Vatican City", currency: "EUR", regions: ["Vatican City"] },
  { code: "VE", name: "Venezuela", currency: "VES", regions: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"] },
  { code: "VN", name: "Vietnam", currency: "VND", regions: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho", "Binh Duong", "Dong Nai", "Ba Ria-Vung Tau", "Khanh Hoa", "Thua Thien-Hue"] },
  { code: "YE", name: "Yemen", currency: "YER", regions: ["Sana'a", "Aden", "Taiz", "Al Hudaydah", "Ibb"] },
  { code: "ZM", name: "Zambia", currency: "ZMW", regions: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Chingola"] },
  { code: "ZW", name: "Zimbabwe", currency: "ZWL", regions: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"] }
];

export const currencies = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "AUD", name: "Australian Dollar", symbol: "A$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "C$" },
  { code: "CHF", name: "Swiss Franc", symbol: "Fr" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "NZ$" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "SGD", name: "Singapore Dollar", symbol: "S$" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "RUB", name: "Russian Ruble", symbol: "₽" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "PLN", name: "Polish Zloty", symbol: "zł" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "HUF", name: "Hungarian Forint", symbol: "Ft" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "ILS", name: "Israeli Shekel", symbol: "₪" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "VND", name: "Vietnamese Dong", symbol: "₫" },
  { code: "BGN", name: "Bulgarian Lev", symbol: "лв" },
  { code: "HRK", name: "Croatian Kuna", symbol: "kn" },
  { code: "EGP", name: "Egyptian Pound", symbol: "£" },
  { code: "NGN", name: "Nigerian Naira", symbol: "₦" },
  { code: "KES", name: "Kenyan Shilling", symbol: "KSh" },
  { code: "PKR", name: "Pakistani Rupee", symbol: "₨" },
  { code: "BDT", name: "Bangladeshi Taka", symbol: "৳" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "QAR", name: "Qatari Riyal", symbol: "﷼" },
  { code: "KWD", name: "Kuwaiti Dinar", symbol: "د.ك" }
];
